version: "3.2"

services:
  firewall:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./node_modules:/app/node_modules
      - ./src:/app/src
    environment:
      - PASSWORD=${PASSWORD}
      - AUTH=${AUTH}
