mod-enabled: true
mod-default-enabled: false
log-settings:
  format: "%6$s %1$c [%2$s] (%3$s:%4$d) %5$s"
  database: log.db
  hide-verbose: false
  filters: []
  verbose:
    before: ""
    after: ""
  information:
    before: ""
    after: ""
  warning:
    before: ""
    after: ""
  error:
    before: ""
    after: ""
  unknown:
    before: ""
    after: ""
mods:
  Audit:
    enabled: false
  BasicAntiCheat:
    enabled: false
  Blacklist:
    enabled: false
  BossBarSupport:
    enabled: false
  Bus:
    enabled: false
  ChatAPI:
    enabled: false
  CommandSupport:
    enabled: true
  CrashHandler:
    enabled: false
  CustomScoreboard:
    enabled: false
  DebugTool:
    enabled: false
  DynamicMotd:
    enabled: false
  Economy:
    enabled: false
  Essentials:
    enabled: true
    commands:
      transferserver: true
      custom-name: true
      tpa:
        enabled: true
        timeout: 30
      home: true
      warp: true
    database: essentials.db
    world-database: essentials.db
  Experimental:
    enabled: true
    force-experimental-gameplay: false
    education-feature: false
    debug-packs: false
  FlatWorld:
    enabled: false
  FormUI:
    enabled: false
  NetworkStatus:
    enabled: false
  NoEncryption:
    enabled: false
  NullPlayerData:
    enabled: false
  PacketDumper:
    enabled: false
  ScriptingSupport:
    enabled: false
  SpawnProtection:
    enabled: false
  WineFix:
    enabled: false
user-database: user.db