version: "3.2"

services:
  minecraft:
    build: .
    ports:
      - "19132:19132/udp"
      - "19133:19133/udp"
    restart: unless-stopped
    # allow attaching to container
    tty: true
    stdin_open: true
    volumes:
      - ./config:/bedrock-server/config
      - ./worlds:/bedrock-server/worlds
      - ./development_resource_packs:/bedrock-server/development_resource_packs
